apiVersion: v1

kind: Pod

metadata:

  name: quota-mem-cpu-demo-1

spec: 

  containers:

    - name: quota-mem-cpu-demo-ctr-1

      image: nginx

      resources:

        limits:

          memory: "1Gi"

          cpu: "800m"

        requests:

          memory: "700Mi"

          cpu: "400m" 
